// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz4P_86TPjA1orSYlaYBn_59DC6rSjknI',
    appId: '1:895628323111:web:b6fde1c638217545eaa102',
    messagingSenderId: '895628323111',
    projectId: 'hallticket-e9150',
    authDomain: 'hallticket-e9150.firebaseapp.com',
    databaseURL: 'https://hallticket-e9150-default-rtdb.firebaseio.com',
    storageBucket: 'hallticket-e9150.appspot.com',
    measurementId: 'G-7Y32V9KRLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy7C-ITHh5BVXjOIu8yLqR_pNosjBtKJ4',
    appId: '1:895628323111:android:71334a8699197460eaa102',
    messagingSenderId: '895628323111',
    projectId: 'hallticket-e9150',
    databaseURL: 'https://hallticket-e9150-default-rtdb.firebaseio.com',
    storageBucket: 'hallticket-e9150.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARolA_voeRs5kLGJvL48TIdx-aWglq8ss',
    appId: '1:895628323111:ios:34c78ed60ec3d3e9eaa102',
    messagingSenderId: '895628323111',
    projectId: 'hallticket-e9150',
    databaseURL: 'https://hallticket-e9150-default-rtdb.firebaseio.com',
    storageBucket: 'hallticket-e9150.appspot.com',
    iosBundleId: 'com.example.place',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARolA_voeRs5kLGJvL48TIdx-aWglq8ss',
    appId: '1:895628323111:ios:4fc2c870f83924e0eaa102',
    messagingSenderId: '895628323111',
    projectId: 'hallticket-e9150',
    databaseURL: 'https://hallticket-e9150-default-rtdb.firebaseio.com',
    storageBucket: 'hallticket-e9150.appspot.com',
    iosBundleId: 'com.example.place.RunnerTests',
  );
}
